### ISSUE TITLE
"issuance":{"released_at"} publication date is missing

### ISSUE THREAD

**Issue by etj** [geosolutions-it/iso19139_mapx_converter#1]
If publication date is missing in xml file but revision date is present -> `"issuance":{"released_at"}` gets the today's date in JSON. 
  Suggestion: Use default date (01/01/0001) instead.

**Comment by etj** [comment]
In a previous ticket:

> In case the Publication Date field is not provided, the dateStamp field should be used instead for the issuance released date.

This means that if the metadata has just been edited, the `dateStamp` gets the today date, and that is reported into the `"issuance":{"released_at"}` field.

**Comment by antobenve** [comment]
@etj , what you have reported is correct. However, it should only apply to conditions where revision date is NOT present. Otherwise we get a revision date older than the publication date.

**Comment by antobenve** [comment]
I hope my proposition is feasible and that you find it logic.
