### ISSUE TITLE
Parsing ISO dates

### ISSUE THREAD

**Issue by etj** [geosolutions-it/iso19139_mapx_converter#33]
This issue summarizes #1 #30 #31 

ISO19115 metadata can provide these dates:
- metadata date
- data creation date
- data revision date
- data publication date

All of these dates were previously taken in account, but according to what I understood we should ignore the data creation date.

The new implementation follows:
Let's define:
- Default date= 01-01-0001
- Fallback date = ISO metadata date if defined and valid, else default date

.    |  ISO publication date <br>valid | ISO publication date <br>not valid (or non-existent)
---------------|---------------|-------------
**ISO revision date <br>valid**  |  MAPX released = ISO publication <br> MAPX modified = ISO revision| MAPX released = fallback<br> MAPX modified = fallback
**ISO revision date <br>not valid (or non-existent)**  |  MAPX released = ISO publication <br> MAPX modified = ISO publication | MAPX released = fallback<br> MAPX modified = fallback

@antobenve pls confirm this is the desired behaviour

**Comment by antobenve** [comment]
Hi @etj , I had a quick review and I suggest the one below would be a more appropriate schema in line with my feedback. 

If it is possible, I'd like to add the "ISO data creation date" to the **Fallback date strategy** as follows: 
1) data creation date (if defined and valid)
2) metadata date (if defined and valid)
3) Default date.

Finally, please always **respect the order** of dates: "MapX released_at" cannot be more recent than "MapX modified_at". If this is the case, please set "Default date" for "MapX released_at".

<html>
<body>


. | **ISO publication date <br> valid** | **ISO publication date <br> not valid (or non-existent)**
-- | -- | --
**ISO revision date <br> valid** | MAPX released = ISO publication <br> MAPX modified = ISO revision | MAPX released = fallback <br> MAPX modified = ISO revision
**ISO revision date <br> not valid (or non-existent)** | MAPX released = ISO publication<br>MAPX modified = Default date | MAPX released = fallback<br>MAPX modified = Default date


</body>
</html>

**Comment by etj** [comment]
Hi @antobenve , according to [this comment](https://github.com/geosolutions-it/iso19139_mapx_converter/issues/1#issuecomment-585729284) we should not have a modified date older that the publication date.

In case we have:
- data creation date (defined and valid)
- publication date (defined and valid)
- revision date (undefined or invalid),

according to your schema we'll get

- MAPX released = ISO publication date
- MAPX modified = Default date = ISO creation date --> we get a modified date older than the released date.

**Comment by etj** [comment]
Hi @antobenve , I see a couple of issues with your proposed solution:

In case we have:
- data creation date (undefined or invalid)
- metadata date (defined and valid)
--> fallback = metadata date, that could be as recent as today
- publication date (undefined or invalid) 
- revision date (defined and valid) 
--> MAPX released = fallback = today
--> MAPX modified = ISO revision date

According to [this comment](https://github.com/geosolutions-it/iso19139_mapx_converter/issues/1#issuecomment-585729284) we should not have a modified date older than the publication date.

Another bad combination would be:
- data creation date (undefined or invalid)
- metadata date (undefined or invalid)
--> fallback = default date
- publication date (undefined or invalid) 
- revision date (defined and valid) 
--> MAPX released = fallback = default date
--> MAPX modified = ISO revision date

According to #31 " Modified_at should get default date '01-01-0001' in any case except when the releaseDate is provided. ".
In this case we have releaseDate not provieded, and modified date not default.




- data creation date (defined and valid)
- publication date (undefined or invalid)
- revision date (defined and valid)
- 
- (undefined or invalid),




Hi @antobenve , according to [this comment](https://github.com/geosolutions-it/iso19139_mapx_converter/issues/1#issuecomment-585729284) we should not have a modified date older that the publication date.

In case we have:
- data creation date (defined and valid)
- publication date (defined and valid)
- revision date (undefined or invalid),

according to your schema we'll get

- MAPX released = ISO publication date
- MAPX modified = Default date = ISO creation date --> we get a modified date older than the released date.

**Comment by antobenve** [comment]
I see your point about the first example you made. I think this should be treated as follows but please let me know if this is in line with your strategy:
1) We apply the schema.
2) IF <the resulting value of "MapX modified date" is older than the resulting value of "MapX released date" AND "MapX modified date" is NOT "Default Date">, we correct as follows:

- The value of "MapX released date" is edited to Default date

As of your second example I admit I made a mistake in my comment. Things are easier than I wrote by mistake:
" Modified_at should get default date '01-01-0001' in any case except when the **"ISO revision date"** is provided.".
Thus, in your example, the results would be correct.

Is this feasible in your opinion?
